# Generated by Django 3.0.4 on 2021-04-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=100, verbose_name='综艺名')),
                ('type', models.SmallIntegerField(choices=[(0, '脱口秀'), (1, '真人秀'), (2, '搞笑'), (3, '选秀'), (4, '情感'), (5, '访谈'), (6, '音乐'), (7, '职场'), (8, '体育'), (9, '其他')], verbose_name='类型')),
                ('region', models.SmallIntegerField(choices=[(0, '内地'), (1, '香港'), (2, '台湾'), (3, '欧美'), (4, '韩国'), (5, '日本'), (6, '其他')], verbose_name='地区')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('tv', models.CharField(max_length=100, verbose_name='卫视')),
                ('net_platform', models.CharField(max_length=100, verbose_name='网络')),
                ('start', models.CharField(max_length=200, verbose_name='明星')),
                ('review', models.TextField(max_length=500, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '综艺管理',
                'verbose_name_plural': '综艺管理',
                'db_table': 'variety',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100, verbose_name='视频名')),
                ('image_url', models.CharField(max_length=300, verbose_name='图片链接')),
                ('video_url', models.CharField(max_length=300, verbose_name='视频链接')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='variety.Variety')),
            ],
            options={
                'verbose_name': '视频管理',
                'verbose_name_plural': '视频管理',
                'db_table': 'video',
            },
        ),
    ]
