# Generated by Django 3.0.4 on 2021-04-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slide_name', models.CharField(max_length=100, verbose_name='名称')),
                ('image', models.ImageField(null=True, upload_to='slide', verbose_name='图片')),
                ('image_url', models.CharField(max_length=300, verbose_name='图片链接')),
                ('ranking', models.IntegerField(verbose_name='图片链接')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '幻灯片管理',
                'verbose_name_plural': '幻灯片管理',
                'db_table': 'slide',
            },
        ),
        migrations.AlterField(
            model_name='variety',
            name='net_platform',
            field=models.CharField(max_length=100, verbose_name='网络平台'),
        ),
        migrations.AlterField(
            model_name='video',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='variety.Variety', verbose_name='所属综艺'),
        ),
    ]
