# Generated by Django 3.0.4 on 2021-04-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0002_auto_20210415_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='slide_name',
        ),
        migrations.AddField(
            model_name='slide',
            name='desc',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='slide',
            name='jump_url',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='ranking',
            field=models.IntegerField(verbose_name='排序'),
        ),
    ]
