# Generated by Django 3.0.4 on 2021-04-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0004_auto_20210419_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='net_platform',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='tv',
        ),
        migrations.AddField(
            model_name='variety',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='variety',
            name='is_hot',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='variety',
            name='is_recommended',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='variety',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='variety',
            name='platform',
            field=models.CharField(default='', max_length=100, verbose_name='播出平台'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='jump_url',
            field=models.CharField(default='', max_length=255, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='release_date',
            field=models.SmallIntegerField(choices=[(0, '2000'), (1, '2001'), (2, '2002'), (3, '2003'), (4, '2004'), (5, '2005'), (6, '2006'), (7, '2007'), (8, '2008'), (9, '2009'), (10, '2010'), (11, '2011')], verbose_name='上映年份'),
        ),
    ]
