# Generated by Django 3.0.4 on 2021-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0005_auto_20210419_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image_url',
        ),
        migrations.AddField(
            model_name='variety',
            name='image',
            field=models.ImageField(null=True, upload_to='variety', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='video', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='release_date',
            field=models.SmallIntegerField(choices=[(0, '2010'), (1, '2011'), (2, '2012'), (3, '2013'), (4, '2014'), (5, '2015'), (6, '2016'), (7, '2017'), (8, '2018'), (9, '2019'), (10, '2020'), (11, '2021')], verbose_name='上映年份'),
        ),
    ]
