# Generated by Django 3.0.4 on 2021-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0006_auto_20210419_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
