# Generated by Django 3.0.4 on 2021-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0008_remove_video_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='desc',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
    ]
