# Generated by Django 3.0.4 on 2021-04-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0009_auto_20210419_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variety',
            old_name='start',
            new_name='star',
        ),
        migrations.AddField(
            model_name='variety',
            name='year',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default=2021, max_length=4, verbose_name='年代'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variety',
            name='release_date',
            field=models.SmallIntegerField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], verbose_name='上映年份'),
        ),
    ]
