# Generated by Django 3.0.4 on 2021-04-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0010_auto_20210420_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='全网排名'),
            preserve_default=False,
        ),
    ]
