# Generated by Django 3.0.4 on 2021-04-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0011_variety_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='release_date',
        ),
    ]
