# Generated by Django 3.0.14 on 2021-05-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0012_remove_variety_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('ranking', models.IntegerField(verbose_name='排序')),
                ('jump_url', models.CharField(default='', max_length=255, verbose_name='链接地址')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '热词管理',
                'verbose_name_plural': '热词管理',
                'db_table': 'hot_word',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('ranking', models.IntegerField(verbose_name='排序')),
                ('image', models.ImageField(null=True, upload_to='slide', verbose_name='图片')),
                ('jump_url', models.CharField(default='', max_length=255, verbose_name='链接地址')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '明星管理',
                'verbose_name_plural': '明星管理',
                'db_table': 'star',
            },
        ),
    ]
