# Generated by Django 3.0.14 on 2021-06-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0013_hotword_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(null=True, upload_to='star', verbose_name='图片'),
        ),
    ]
