# Generated by Django 3.0.14 on 2021-06-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0014_auto_20210623_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='modified_date',
        ),
    ]
