# Generated by Django 3.0.14 on 2021-06-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variety', '0015_auto_20210623_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='modified_date',
        ),
    ]
