# Generated by Django 3.0.14 on 2021-05-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0014_auto_20210508_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m%d/'),
        ),
    ]
